# Generated by Django 3.2.16 on 2022-12-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0166_sitesettings_imports_enabled'),
        ('bookwyrm', '9001_api_keys'),
    ]

    operations = [
    ]
